source 'https://rubygems.org'


gem 'rails', '4.2.4'
gem 'pg'
gem 'jbuilder', '~> 2.0'
gem 'omniauth'
gem 'omniauth-paypal'
gem 'dotenv'
gem 'rack-cors'
gem 'pundit'
gem 'turbolinks'
gem 'sass-rails'
gem 'jquery-rails'

group :development, :test do
  gem 'pry-byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
end

